openapi: 3.0.0
info:
  title: ChatContext API
  version: 0.0.0

paths:
  # *******************************************************************************
  #                           Admin
  # *******************************************************************************
  /api/getCounters:
    get:
      summary: GetCounters
      operationId: getCounters
      tags:
        - Admin
      responses:
        '200':
          description: Result