server:
  port: 7040
  servlet:
    session:
      timeout: 86400
  externalUrl: http://localhost:7040

spring:
  main:
    banner-mode: "off"

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  application:
    name: chatcontact

  pid:
    file: /opt/chatcontact/bin/${id:application}.pid
    fail-on-write-error: true

  mvc:
    throw-exception-if-no-handler-found: true

  datasource:
    url: jdbc:postgresql://localhost:5432/chatcontact

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      ddl-auto: none #create #update

  flyway:
    enabled: false

logging:
  file: ${log.dir:/tmp}/main.log
  file.max-history: 90
  file.max-size: 100MB
  long-request-time: 1000
  request-body-characters: 1000

embedder:
  url: http://95.217.152.181:8889